### ISSUE TITLE
Localized Lookup

### ISSUE THREAD

**Issue by Tickthokk** [freemarker/fmpp#12]
Hello.  First, thanks for maintaining this project!

Second, I'd like to apologize for bringing up something that was done [Twelve years ago](http://fmpp.sourceforge.net/versions.html#sect20) :stuck_out_tongue: 

I'm interested in FreeMarker's [Localized Lookup](http://freemarker.org/docs/ref_directive_include.html#ref_directive_include_localized) functionality.  Can we turn this on?

Within the FMPP Engine.java file, line 301:

```
fmCfg.setLocalizedLookup(false);
```

I was wondering what the "confusing effects" referenced in the change log would be if I set that to `true`.

Thank you!

**Comment by ddekany** [comment]
That basic logic of FMPP is that goes through all the files in the source root directory one by one, and generates a file with identical name in the output root directory. Thus, if you have `foo_de.txt` and `foo_es.txt` and `foo.txt`, FMPP will generate 3 output files with those exact file names, instead of a single `foo.txt` that's based on one of the 3 sources based on the current locale. Furthermore, in this example, when FMPP processes `foo.txt`, and FM's localized lookup was on, and your locale is `de`, then because FM will load `foo_de.txt` despite FMPP told him to load `foo.txt`, you again end up with 3 output files, but now two of them will be based on `foo_de.txt`, one on `foo_es.txt`, and none will be based on `foo.txt`. So that's why localized lookup is off... it's not compatible with FMPP.

**Comment by Tickthokk** [comment]
Great explanation.  Makes sense not to turn it on.  Thanks!
